print("Hey I Know Your SECRETS")
print("I will give 90 days then i will reveal your secrets")
print("I will give 90 days then i will reveal your secrets")
print("????>>><<<:::")
print("hi hello nice to meet you ")
print("00!!")
print("hi iam here")
print("????>>><<<:::")
print("hi hello nice to meet you ")
print("00!!")
print("hi iam here")
print("jasbnfjnsjfas")
print("asnjasbnfjsnajf")

